version: '3.9'

services:
  mysqldb:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: customfunctionsinlambdas
    volumes:
      - mysql-data:/var/lib/mysql

  webapi:
    build:
      context: ./DotnetExamples.EntityFramework.CustomFunctionsInLambdas
    ports:
      - "5000:8080"
    depends_on:
      - mysqldb
    environment:
      ASPNETCORE_ENVIRONMENT: Development

volumes:
  mysql-data: